### ISSUE TITLE
Magiclysm revamp addition

### ISSUE THREAD

**Issue by rhyphix** [Kenan2000/BrightNights-Structured-Kenan-Modpack#112]
Seem to be having a problem trying to get this mod to run along side magiclysm.

I get this as a debug log when trying to run it, a bunch of invalid attack effects; should I go back to a previous version to run this mod?

12:48:13.889 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell acid_bite has invalid effect attack
12:48:14.263 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_bite has invalid effect attack
12:48:14.617 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_shell_retaliation_black has invalid effect attack
12:48:14.865 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_terror has invalid effect attack
12:48:15.368 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_boost has invalid effect attack
12:48:15.399 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell health_recovery has invalid effect attack
12:48:15.445 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_spit_acid has invalid effect attack
12:48:15.476 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_breath_acid has invalid effect attack
12:48:15.507 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell dragon_breath_black has invalid effect attack
12:48:15.554 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell spy_wasp has invalid effect attack
12:48:15.570 ERROR DEBUGMSG : src/generic_factory.h:467 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = field_type]] invalid field types id "fd_clairvoyant"
12:48:15.603 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell nitro_boost has invalid effect dash
12:48:15.633 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell biotek_healing has invalid effect attack
12:48:15.665 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell banishment_greater has invalid effect banishment
12:48:15.698 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell auroral_wave has invalid effect attack
12:48:15.728 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell auroral_wave_cold has invalid effect attack
12:48:15.777 ERROR DEBUGMSG : src/magic.cpp:258 [void spell_type::load(const JsonObject&, const string&)] ERROR: spell immolate has invalid effect attack
12:48:15.806 ERROR DEBUGMSG : src/main_menu.cpp:1152 [bool main_menu::load_character_tab(bool)] Error: Json error: data/mods/MagicRevampAdditions/Spells_Override/attunements/Cleansing_Flame.json:38:71: invalid flags: "IGNITE_FLAMMABLE"

ntal heat wipes the slate clean, searing the Earth back to her most original state: a barren ball of burning rock.",
    "valid_targets": [ "ally", "hostile", "ground" ],
    "flags": [ "SOMATIC", "VERBAL", "NO_LEGS", "LOUD", "CONCENTRATE", "
                                                                      ^
                                                                       IGNITE_FLAMMABLE", "MUST_HAVE_CLASS_TO_LEARN" ],
    "effect": "attack",
    "shape": "blast",
Edit:  Seems going back to the previous version fixed everything for me, but this was the debug log on the newest experimental version at the time for my case.

**Comment by Kenan2000** [comment]
@rhyphix All of these spells that are specified in debug log that you've posted are from CDDA MagicRevampAdditions version, they don't exist in Bright Nights MagicRevampAdditions version. Have you downloaded mods for Bright Nights from this link, not my CDDA Modpack, right? If you want to download mods that I maintain for Bright Nights, you need to download them from this link, Bright Nights Modpack, feel free to ask me any other questions about mods as well

**Comment by rhyphix** [comment]
Sorry it seems I must have done that by mistake,  I think initially installed everything from the cdda pack, then installed the bright night version and must have encountered those incompatibilities, reinstalling everything from the bright night version pack fixed these issues.
