### ISSUE TITLE
[Wild Living] Taking a Cutting from a fruit tree don't actually generate cutting to pot

### ISSUE THREAD

**Issue by Ker-Nes** [Kenan2000/BrightNights-Structured-Kenan-Modpack#113]
Bug:
Using the construction menu to take a cutting of a fruit tree (and the tree doesn't seem to recover, although I haven't quite been able to test that one out properly) doesn't seem to actually generate the cutting that is necessary to pot it and eventually plant. 

Expected behavior:
The action to generate a cutting item.

Bug tested with in the following circunstances:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5d36160 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Wild Living [WildLiving]
]

**Comment by Kenan2000** [comment]
@Ker-Nes Hopefully fixed in this update as well
