### ISSUE TITLE
Errors in Project Apex

### ISSUE THREAD

**Issue by Nitsua1230** [Kenan2000/BrightNights-Structured-Kenan-Modpack#115]
A couple of errors pointing towards euler os items
![Screenshot (41)](https://user-images.githubusercontent.com/63229009/179339428-d23396f8-f185-4b30-8725-dfa60bd5698f.png)
![Screenshot (42)](https://user-images.githubusercontent.com/63229009/179339430-908f93ef-7db6-428a-9db6-0eea395f0430.png)
![Screenshot (44)](https://user-images.githubusercontent.com/63229009/179339431-706800d7-7292-449f-aa31-e187f463a84e.png)
![Screenshot (45)](https://user-images.githubusercontent.com/63229009/179339434-9cd96ff6-a50a-401a-a6c6-f6eeb672b6ee.png)
.

**Comment by Kenan2000** [comment]
@Nitsua1230 Hopefully fixed in this update as well
