### ISSUE TITLE
[wild living] Minor Recipe Inconsistency between potting trees

### ISSUE THREAD

**Issue by Ker-Nes** [Kenan2000/BrightNights-Structured-Kenan-Modpack#116]
The recipe for potting the apple tree is not in line with the rest. For reference:
![image](https://user-images.githubusercontent.com/37450179/179615865-d868d0d1-66b5-4558-80c9-dd520ece5353.png)
![image](https://user-images.githubusercontent.com/37450179/179615863-98d664d6-b77f-4a16-85ae-cf58b1c61164.png)
All other potted tree recipes are essentially identical to the pear recipe (save for the actual fruit, of course). Apple trees also take 1 soil and take 20 minutes to pot, while the rest take a bit under 2 minutes and don't take any soil.

Either side should probably be brought in line with the other.

For reference:
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5d36160 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Elevated bridges [elevated_bridges],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Advanced Gear [adv_gear],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Bens GF recipes* [Tolerate_This__],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Culinary Days Ahead [culinary_days_ahead],
    DeadLeaves' Fictional Guns* [FIC_Weapons__],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Gourmand's Graces [Gourmand'sGraces],
    Icecoon's Arsenal* [ew_pack__],
    Kingsman Umbrella [kingsman],
    Large capacity storage CBMs [eps_cbm],
    Makeshift Items Mod* [makeshift__],
    Metal materials [metal_elemental],
    MOD to grow tea leaves [More tea leaf],
    More Armors [More_Armors],
    More Makeshift Stuff [makeshift_stuff],
    Nimian Manufacture Guns [NM_wpns],
    Pipe Revolver Rifles [pipe_revolver_mod],
    Pixel's Various Fuckery [Pix's Shit],
    Pressure Weapons [pressure_weapon],
    Ricky's Future Armory [futurearmory],
    Rivtech Beam Swords [beamswordmod],
    Survivor's Lost item [Survivors_Lost_item],
    Survivor crowbar [surv_crowbar],
    The Vermilion Mod [VermilionMod],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    Bug's life [Bug's life],
    Draco's Pig Mod [DracoPigMod],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Mutant Insects [mutant_insects],
    Salvaged Robots* [Salvaged_Robots__],
    Crazy Labs [crazy_labs],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Alternative Map Key [alt_map_key],
    CDDA Variety Pack [ks_variety_pack],
    Hydroponics* [hydroponics__],
    Crazy Pets! [crazypets],
    Jury-Rigged Robots [jury_rigged_robots],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs* [mutant_npcs__],
    Wandering Masters [wandering_masters],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Water Towers [water_towers],
    Folding Parts pack* [deoxymod__],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Pneumatic fun [pneumo_fun],
    Blazemod - Vehicle Additions Pack* [blazemod__],
    No Explosive Zombies [No_Explosive_Zombies],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Fuji's Military Profession Pack [fuji_mpp],
    Gunslinger Mod [MkMaxxi's Gunslinger Mod],
    Manual Bionic Installation [manualbionicinstall],
    Necropolis Actually Findable [necro_find],
    Targeted Mutations [TaMu],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp],
    Draco's Dog Mod [DracoDogMod],
    No Fungal Monsters [No_Fungi],
    Simplified Nutrition [novitamins]
]

**Comment by Kenan2000** [comment]
@Ker-Nes Hopefully fixed in this update as well
