### ISSUE TITLE
Issue regarding the latest release - PK Rebalancing

### ISSUE THREAD

**Issue by T3hBoy** [Kenan2000/BrightNights-Structured-Kenan-Modpack#117]
![01](https://user-images.githubusercontent.com/108841169/180332064-2fbd0699-9ba3-4c54-af88-4894058e3ebe.png)

**Comment by Kenan2000** [comment]
@T3hBoy Hopefully fixed in this update as well

**Comment by T3hBoy** [comment]
All good, thanks
