### ISSUE TITLE
[More Makeshift Stuff] Makeshift Canoes and Rafts folding into bicycles. 

### ISSUE THREAD

**Issue by Ker-Nes** [Kenan2000/BrightNights-Structured-Kenan-Modpack#118]
Makeshift canoes and makeshift rafts are created as items that can then be unfolded into the vehicles in question. When interacting with them the option to "fold" them back up is available. 
![image](https://user-images.githubusercontent.com/37450179/180629610-ae0d8d93-5ef5-48e5-bcb3-b5733df6c292.png)
But doing so, folds them into being a folding bicycle. 
![image](https://user-images.githubusercontent.com/37450179/180629634-bbefc258-5839-4a76-8c29-d353e05251ae.png)
Which behaves like a normal folding bicycle from thereon now. 
![image](https://user-images.githubusercontent.com/37450179/180629648-75f9e5b1-5505-425e-9c0f-82240420d0e7.png)

**Comment by Kenan2000** [comment]
@Ker-Nes This is vanilla game issue essentially
