### ISSUE TITLE
[Vermillion_mod] Augmented Swordplay martial art techniques missing "melee_allowed": true tags

### ISSUE THREAD

**Issue by Usokitsuki** [Kenan2000/BrightNights-Structured-Kenan-Modpack#123]
As the issue name suggests. While martial art buffs in the actual ver_martialarts.json properly have the tags and function, none of the techniques in the ver_techniques.json do, rendering them unusable. Adding the tag solves the issue.

Due to similarity with #122 , it is entirely possible there are more mods adding martial arts and corresponding techniques that are missing the tags.

**Comment by Kenan2000** [comment]
@Usokitsuki Hopefully fixed in this update as well
