### ISSUE TITLE
CDDA-BN-Biosynthetic-Robot-Mod crash

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/BrightNights-Structured-Kenan-Modpack#127]
Firing at robots from the mod with the hypervelocity drive at close range causes a ctd. No error message or anything.

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 937decd [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Arcana and Magic Items [Arcana],
    Aftershock [aftershock],
    Cataclysm++ [Cata++],
    Battle Maid Redux [battle_maid],
    Bio-Synth Robot expansion [gekkobots],
    C.R.I.T Expansion Mod [crt_expansion],
    Elevated bridges [elevated_bridges],
    Magiclysm [magiclysm],
    Nechronica Redux [Nechronica_Redux],
    Steampunk Mod [steampunk_arcanum],
    Valkyria Chronicles Mod [valchron_mod],
    UnderrailMetro Mod [underrailmetro_mod],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Advanced Technologies [advtech],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    anti-fungal gear [anti_fungal_gears],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Bens GF recipes* [Tolerate_This__],
    Bionics Systems Recipes [bio_recipes],
    CBM Equipment [CBM_Arms],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Culinary Days Ahead [culinary_days_ahead],
    DeadLeaves' Fictional Guns* [FIC_Weapons__],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Garden Pots* [growable-pots__],
    Gourmand's Graces [Gourmand'sGraces],
    Homemade Fungicide [homemade_fungicide],
    Large capacity storage CBMs [eps_cbm],
    Makeshift Items Mod* [makeshift__],
    Metal materials [metal_elemental],
    MOD to grow tea leaves [More tea leaf],
    More Armors [More_Armors],
    More Survivor Notes [more_survive_notes],
    Mythological Replicas* [nw_pack__],
    Pixel's Various Fuckery [Pix's Shit],
    Pneumatic fun [pneumo_fun],
    Pressure Weapons [pressure_weapon],
    ProjectKawaii [ProjectKawaii],
    Rivtech Beam Swords [beamswordmod],
    The Glory Of Cereal! [CerealMod],
    The Vermilion Mod [VermilionMod],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    Bug's life [Bug's life],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    Salvaged Robots* [Salvaged_Robots__],
    Youkai Enemies [Youkai_Disco],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    CDDA Variety Pack [ks_variety_pack],
    Hydroponics* [hydroponics__],
    Jury-Rigged Robots [jury_rigged_robots],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs* [mutant_npcs__],
    NPC Recruitment Options [recruitment_options],
    Sarcophagi Access [sarcophagi_access],
    Wandering Masters [wandering_masters],
    Beta National Guard Camp* [national_guard_camp__],
    Caches [P_Caches],
    Water Towers [water_towers],
    Trailer Parks [trailerpark],
    Blazemod - Vehicle Additions Pack* [blazemod__],
    Folding Parts pack* [deoxymod__],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles* [Heavy miners__],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Amplified @'s Features [amplified_players_features],
    Graphical Overmap [Graphical_Overmap],
    Mutation Changes Snofielf [Mutation_Changes1],
    Shinigami [shinigamimod],
    Stats Through Kills [stats_through_kills],
    Targeted Mutations [TaMu],
    Vehicle Additions Pack [blazemod],
    Vehicle Additions Additions [blaze_extension_M],
    Stronger archery [bow_opness]
]

**Comment by Kenan2000** [comment]
@Nephelos It's a very weird game issue that needs more details in order to fix this mod, can you test other guns on monsters from this mod? Can you test multiple monsters from this mod? Is it because of gun that you use against them in your opinion or is it because of monsters themselves? What exactly needs fixing here, can you clarify hopefully?

**Comment by Nephelos** [comment]
Every other weapon i used on them was fine. I think its the shrapnel mechanic since the hypervelocity drive is mounted on my armored death truck and if they are like inside a 10-15 tile radius and shoot them it ctds the game.
