### ISSUE TITLE
Advanced Gear - cannot progress to next tier of nanite construction tool

### ISSUE THREAD

**Issue by Relgar** [Kenan2000/BrightNights-Structured-Kenan-Modpack#137]
In the Advanced Gear mod, you supposedly upgrade your nanite construction tool by building a Nanofactory (3d printer) as the next level, which takes a significant amount of nanotech power cells. However, to build these power cells, which are suggested to be from plutonium, you need feedstocks of various kinds, plutonium, and then _the upgraded nanite construction tools which you're trying to build in the first place_, leading to a Catch-22.

Solution: allow the level 1 nanite tool to build nanotech power cells

![image](https://user-images.githubusercontent.com/84274761/203779410-c0af0612-b298-49e8-9f2f-31b090fe3896.png)

![image](https://user-images.githubusercontent.com/84274761/203779541-f3f7f8fa-c2fe-43d5-ab25-de1c17ea0840.png)

**Comment by Kenan2000** [comment]
Hmm, accessible nanite tool that can easily craft nanite power cells to make more advanced types of nanite tools that requires no crafting is experimental nanite assembler, it can be found in science, teleport item groups which are labs spawns mostly, I have increased spawn chance of it in science item group from 2 to 25, I have also increased spawn chance of it in teleport item group from 5 to 45, this should make nanotech crafting in general much more accessible in it hopefully
