### ISSUE TITLE
Dependencies on Bright Nights Split between two versions

### ISSUE THREAD

**Issue by fg094** [Kenan2000/BrightNights-Structured-Kenan-Modpack#139]
I noticed that half of the mods require "bright nights [dda]" and the other half require "bright nights [bn]" which means that half of the mods can't be used together.

For example Psychiclysm wants [dda] and magiclysm wants [bn] so they can't be selected together.

**Comment by Nightrealm** [comment]
[BN] just redirects to the games base files and [dda] just fixes compatibility and formatting issues not updated to [BN] yet and its also a requirement as far as i know and read the mod info so you can play with them together. also it seems to be likely that the [dda] might be removed next stable bright nights patch.

**Comment by fg094** [comment]
the problem is that it won't let me select the [dda] and [bn] together. so if I add a [bn] mod to the world mod list it deslects [dda] and all [dda] mods.

I just used notepad++ to change all instances of [dda] to [bn] in the modinfo files and that seems to be working so far with no errors.

**Comment by Kenan2000** [comment]
@fg094 I have carefully updated all mods, in general I try to update all mods carefully, in my Bright Nights Modpack to make sure that all modinfo.json files use bn, one can check this using GitHub search function, if you are using launcher, please, do not use it to install mods, use it for game installation only, install all mods manually for safe installation hopefully as well

**Comment by fg094** [comment]
I didn't use the launcher at all. I downloaded directly from the github here and brought the files from the large mods and small mods folders over into the BN mods folder as the instructions say into a fresh download of bn.

**Comment by fg094** [comment]
ah, I found the problem. the latest release (oct 11) still has [ "dda" ] in several modinfo files but it has been corrected in the code since then.
