### ISSUE TITLE
Mapgen issues in some mods

### ISSUE THREAD

**Issue by olanti-p** [Kenan2000/BrightNights-Structured-Kenan-Modpack#140]
Recently we've [ported](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2197) DDA's mapgen size checks to BN, so now some of the mods can't load 

(reported on Discord)

![image](https://user-images.githubusercontent.com/60584843/208664769-d9e35efe-2299-405a-b86a-b7be8fb159a6.png)

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
