### ISSUE TITLE
Error in fridge_item.json

### ISSUE THREAD

**Issue by yay855** [Kenan2000/BrightNights-Structured-Kenan-Modpack#142]
New error, for... some reason. I got it when I updated the game, before which it was working just fine.

 DEBUG    : Error: Json error: ./mods/Expansion_Tefnut/items/vehicle_parts/fridge_item.json:EOF: tried to start object, but found '�', not '{'

 FUNCTION : load_character_tab
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp
 LINE     : 1155
 VERSION  : BN 0b44cbc

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
