### ISSUE TITLE
a suggestion for advancedgear

### ISSUE THREAD

**Issue by zantanzuken** [Kenan2000/BrightNights-Structured-Kenan-Modpack#160]
currently as the mod is, you can go into labs and find/break jars that have bio nanites, but they dont work as regular nanites... i also noticed that there is a recipe that allows for you to basically 'grow' these bio nanites in order to have an infinite supply.

rather than growing bio nanites that do nothing, my suggestion is this: change the output for the growth tank from more bionanites to just nanite clusters, so that say, 25 bio nanites can be grown along with organic components into 250 usable nanite clusters, giving both items an actual use until lorith decides to do something with it? (which they probably wont considering last updates were in 2019) alternatively, have bio nanites clone their function from nanite clusters so that they can also be used in relevant recipies (though this would allow you to grow bionanites infinitely, kinda breaking the mod difficulty)

**Comment by zantanzuken** [comment]
basically:

> [
  {
    "type" : "recipe",
    "result": "bio_nanite_spawning",
    "category": "CC_NANO",
    "subcategory": "CSC_NANO_NANITES",
    "skill_used": "fabrication",
    "skills_required" : [ "fabrication", 3 ],
    "difficulty": 0,
    "time": "1 m",
    "reversible": false,
    "book_learn": [ [ "nanite_core_3", 1 ], [ "nanite_core_4", 1 ] ],
    "qualities": [
      {"id":"NANOTECH","level":3,"amount":1},
      {"id":"NANO_PRO","level":2,"amount":1}
    ],
    "components": [
      [
        [ "water", 5 ],
        [ "water_clean", 5 ]
      ],
      [
        [ "offal", 2 ],
        [ "meat", 2 ],
        [ "human_flesh", 2 ],
        [ "stomach_large", 2 ],
        [ "hstomach_large", 2 ],
        [ "stomach", 2 ],
        [ "hstomach", 2 ],
        [ "bone", 2 ],
        [ "bone_human", 2 ]
      ],
      [
        [ "offal", 2 ],
        [ "meat", 2 ],
        [ "human_flesh", 2 ],
        [ "fat", 2 ],
        [ "stomach_large", 2 ],
        [ "hstomach_large", 2 ],
        [ "stomach", 2 ],
        [ "hstomach", 2 ]
      ],
      [
        [ "3d_resin_metal", 50]
      ],
      [
        [ "3d_resin_electronic", 50]
      ],
      [
        [ "metal_tank", 1]
      ],
      [
        [ "bio_nanites", 25]
      ],
      [
        [ "nanite_power_cell", 4]
      ]
    ]
  },{
    "type": "uncraft",
    "result": "bio_nanite_spawned",
    "skill_used": "fabrication",
    "difficulty": 0,
    "time": "30 s",
    "components": [
        [ [ "nanite_cluster", 250 ] ],
        [ [ "metal_tank", 1 ] ]
    ]

in advanced gear's recipies - production - nanites.json

**Comment by Kenan2000** [comment]
@zantanzuken I have included your name in commit because of your suggestion based on which I have made a mods update with a small tweak of slightly reducing your proposed value to keep original mod balance honestly. Hopefully fixed in this update as well
