### ISSUE TITLE
Bens GF Recipes (Tolerate_This) has broken recipe

### ISSUE THREAD

**Issue by megu230** [Kenan2000/BrightNights-Structured-Kenan-Modpack#169]
A certain recipe in Tolerate_This lacks the `"result"` object, causing it to show as `none` in-game. Seems to be some sort of chocolate bread? I'm not sure.
![notepad++_2023-11-04_05-19-32](https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack/assets/18707967/3ac9e350-11de-4c7d-a71e-0bd5334868ea)
![cataclysm-tiles_2023-11-04_05-20-33](https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack/assets/18707967/613d007c-0055-4a03-b339-572945da9d88)

**Comment by Kenan2000** [comment]
@megu230 Hopefully fixed in this update as well
