### ISSUE TITLE
PK's Rebalancing Causes Fatal Crashes After Latest Experimental Release

### ISSUE THREAD

**Issue by DrPariah** [Kenan2000/BrightNights-Structured-Kenan-Modpack#174]
DESCRIBE THE ERROR: Attempting to generate a world with PK's active causes a fatal error and crash to desktop.

STEPS TO REPRODUCE:
- Generate a world with PK's Rebalance active
- Complete character generation
- Cry a lot as your game crashes

Appears to be related to [https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4154](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4154), Triffid related. PK's is one of the only mods to mess with Triffid overmap stuff, and doesn't reflect the current method of generation in the PR referenced above. It flags for unknown overmap terrain in the debug file.

Not sure how to fix it properly, though I did get it working by deleting the Triffid overmap references in PK's.

**Comment by Kenan2000** [comment]
@DrPariah Hopefully fixed in this update as well

**Comment by Zlorthishen** [comment]
> did get it working by deleting the Triffid overmap references in PK's.
you'll have to remove all referances to `triffid_roots` and `triffid_final` because they don't exist anymore
