### ISSUE TITLE
Minor issue with Bone-pickaxe, within Wild_Living mod

### ISSUE THREAD

**Issue by Craftomega** [Kenan2000/BrightNights-Structured-Kenan-Modpack#176]
https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack/blame/9399c71f616b7512fe46fe6df7ad47931709ae9a/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Wild_Living/bone-pickaxe.json#L13

bone-pickaxe issue
[" textbook_survival", 4 ]
Should be, without extra space.
["textbook_survival", 4 ]

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
