### ISSUE TITLE
FIRE_20 flag no longer exists in BN, update to NAPALM

### ISSUE THREAD

**Issue by Relgar** [Kenan2000/BrightNights-Structured-Kenan-Modpack#182]
It's been a while since I played with this pack, the below hinted this issue to me:
Modular Turrets throws this alert.

 DEBUG    : robogun_flame has unknown ammo_effect FIRE_20, removing

 FUNCTION : operator ()
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\item_factory.cpp
 LINE     : 324
 VERSION  : BN 69ceb70

**Comment by Kenan2000** [comment]
Update mods manually, there is no such error in newest version of Modular Turrets, erase old Modular Turrets folder that is prepackaged with older version of game then install newer version if you don't mind
