### ISSUE TITLE
PKS Rebalancing - Monster Errors

### ISSUE THREAD

**Issue by MisterWytt** [Kenan2000/BrightNights-Structured-Kenan-Modpack#186]
Using the latest Bright Nights nightly, and PKs is spouting some errors with a few monsters. Was wondering if you could take a look? It lets me continue the game, but I just wanna make sure it doesn't error out or anything later on.

![pk1](https://github.com/user-attachments/assets/a348dfdf-f535-4461-8928-cd69c562c1c2)
![pk2](https://github.com/user-attachments/assets/591d944c-cd6f-4517-9161-10b4ca84b97a)
![pk3](https://github.com/user-attachments/assets/3e29dfde-39e4-4996-bfc2-ddeedf0052a5)

**Comment by Kenan2000** [comment]
So did you read README? Like, literally, I do not update any of this work for any of forks of this game anymore. Zlorthishen is now the maintainer of this work for Bright Nights so post these in his repository, ping him on discord if you don't mind to do that obviously

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Maybe you should put that in the README then, there is no mention of Zlorthishen and no link to the maintained version.
https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack
