### ISSUE TITLE
Fallout New England - Map Errors

### ISSUE THREAD

**Issue by MisterWytt** [Kenan2000/BrightNights-Structured-Kenan-Modpack#187]
Also getting some errors with some of the areas it maps out. This one would probably be a bit more serious.

![fo1](https://github.com/user-attachments/assets/93def42f-aea1-4aec-942c-e4d7d7826835)
![fo2](https://github.com/user-attachments/assets/46f9db9d-9ad8-4b90-883c-c96efabd34ca)
![fo3](https://github.com/user-attachments/assets/c5b8b207-71cf-4e0f-b90d-e782151a8026)
![fo4](https://github.com/user-attachments/assets/ad7c481a-634d-4bd6-b89b-33c8cb822af3)

**Comment by Kenan2000** [comment]
So did you read README? Like, literally, I do not update any of this work for any of forks of this game anymore. Zlorthishen is now the maintainer of this work for Bright Nights so post these in his repository, ping him on discord if you don't mind to do that obviously hopefully
