### ISSUE TITLE
Syntax Error in Vamp_Stuff_Arcana mod

### ISSUE THREAD

**Issue by KoRv117** [Kenan2000/BrightNights-Structured-Kenan-Modpack#69]
![Syntax Error](https://user-images.githubusercontent.com/56089860/143306421-f94e0202-2379-4acb-9475-db20cad1dca4.png)

I get this message when im trying to load the game, not sure if its the mod itself or if its caused by another mod? Ill add the mod list just to be safe.

[
  "dda",
  "Arcana",
  "magiclysm",
  "Cata++",
  "no_npc_food",
  "Medieval_Mod_Reborn",
  "DracoDogMod",
  "necromancy",
  "TaMu",
  "No_Fungi",
  "stats_through_kills",
  "speedydex",
  "demon_spider_a",
  "craftgp",
  "ExArch",
  "materials_plants",
  "pressure_weapon",
  "space_heater",
  "pneumo_fun",
  "blazemod",
  "hydroponics",
  "incinerator",
  "Dorf_Life",
  "wandering_masters",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "recruitment_options",
  "DracoPigMod",
  "thermal_ups",
  "CerealMod",
  "SD_Magcrafting"
]

**Comment by CV514** [comment]
This happens because `u_spend_cash` is not used in NPC trades anymore as of recently https://github.com/cataclysmbnteam/Cataclysm-BN/pull/842

This may be "robust-fixed" by removing said effect from this file, but in general should be looked into and considering more balanced alternatives.

**Comment by Kenan2000** [comment]
Hopefully these errors are fixed in latest updates as well
