### ISSUE TITLE
Targeted Mutations crash (Full Nightvision serum)

### ISSUE THREAD

**Issue by Roet718** [Kenan2000/BrightNights-Structured-Kenan-Modpack#76]
Noticed that the night vision and infrared vision serums were having no effect in my game. So I made a test world with only Targeted mutations in it and got a crash every time I tried to inject those serums.

**Comment by CV514** [comment]
I've tested BN+Targeted Mutations, all night vision related mutations are working correctly. Infrared serum must be injected several times on "regular" character to produce IR effect, and it will be passive, while night vision must be activated manually in the mutations menu. 

But nothing is crashing, so can't reproduce.

Please provide crash error text (use `debug.log` inside 'config' folder) and basic info about your game: 
Escape - Debug Menu - Info - Generate game report
I'll be saved into `debug.log` and to the clipboard.

**Comment by Roet718** [comment]
In my main game, i tried spawning in 20 of the serums and taking them all, but nothing happened, there was no text output or anything. just got pain and thirst from it. 
But in the test world I made, I am no longer able to replicate the crash. So I have no idea.  Im ok to close this unless you have any ideas.

**Comment by CV514** [comment]
If you still got your problematic save file, you can toss it here, I'll look into it.

**Comment by Roet718** [comment]
[#Um9ldA==.zip](https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack/files/7872490/Um9ldA.zip)

Alright, thanks. At first, I thought it could be the paragon of veil threshold from Arcana. but I removed all traces of that from the save files, and infrared vision is not a threshold mutation anyway. Also, all other TagMu serums seem to work just fine.

**Comment by CV514** [comment]
Ah, forgot to mention - you should pack not just char save, but world as well since all the mods info, world cells and relevant log files are tied together. Just pack the whole `worldname` folder to be sure.

**Comment by Roet718** [comment]
Alright trying that but it just says "is not included in the list" it's 55Mb is that too big for it ?

**Comment by CV514** [comment]
It would seem so, world data is taking some space indeed. You can toss it via cloud service of your choice.

**Comment by Roet718** [comment]
Yeah ive been playing in it for quite some time. ok here it is. https://drive.google.com/file/d/11YGsIwYrN7DWmP7zfPTSF_6PqwwV9EPU/view?usp=sharing

**Comment by CV514** [comment]
Alright, your character have telescopic eyes installed. This is actually fully replacing them eyes with machinery, rendering all beneficial mutations non-valid and canceling any existing ones. This is base game balance question and here is open discussion about it: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1190

Outside of this scope, everything seems to be working fine.

**Comment by Roet718** [comment]
Omg. Thanks so much. I was poring over the save file trying to find any leftover threshold information, I never would have figured that out.

**Comment by CV514** [comment]
To test that you can simply use Bionic Operator from Aftershock and Targeted Mutations mod in new world and new save, nothing else.
If you want to edit your character, I think we don't have the meanings to debug uninstall bionics right now. There is debug bionics installation mutation available, but this is for installation only, right from inventory.

You can edit your save file, find then remove the following:
`{ "id": "bio_eye_optic", "invlet": 100, "powered": false, "charge": 0, "ammo_loaded": "null", "ammo_count": 0, "bionic_tags": [  ] },`
and
`{ "bionic": [ "bionic_id", "bio_eye_optic" ], "character": [ "character_id", "1" ] }, 1 ],`

this will remove telescopic eyes from your character.

**Comment by Roet718** [comment]
Alright, that did it! infrared vision mutation is working on the character now! thanks so much. I'll close this.
