### ISSUE TITLE
From the Secronom mod, the "secro_power_armor_mechlink" spell ID is invalid

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#77]
This appears to be connected to the flesh vessel mech, which is a part of the Secronom Project - Experimental scenario. Here is what appears in the log
https://pastebin.com/2GZvt1Qm

**Comment by Kenan2000** [comment]
@Spodershibe Hopefully fixed in this update as well

**Comment by Kenan2000** [comment]
@Spodershibe Hopefully fixed in this update as well
