### ISSUE TITLE
Oa's Additional Buildings Mod does not stay in active mods list

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#80]
When I add Oa's Additional Buildings Mod to a worlds mod list, and then I load up a character on that world, the next time I look at the mods list, Oa's Additional Buildings Mod has automatically disabled itself. Nothing appears in the logs for this, I don't know how to be more helpful than this for this issue.

**Comment by Kenan2000** [comment]
@Spodershibe Hopefully fixed in this update as well
