### ISSUE TITLE
Many new Real Dark Skies Above issues

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#82]
The main mod has been updated to fix whatever issue this is

**Comment by Kenan2000** [comment]
@Spodershibe Have these issues been fixed? Can you clarify?

**Comment by Spodershibe** [comment]
> @Spodershibe Have these issues been fixed? Can you clarify?

Yes, the main Real Dark Skies above mod had some kind of major bug in it and the author updated it to solve it
