### ISSUE TITLE
Game freezing error in Metro mod (Tried to set invalid ammo)

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#83]
Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag
22:16:02.308 ERROR DEBUGMSG : src/item.cpp:605 [item& item::ammo_set(const itype_id&, int)] Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag
22:16:03.092 ERROR DEBUGMSG : src/item.cpp:605 [item& item::ammo_set(const itype_id&, int)] Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag
22:16:03.639 ERROR DEBUGMSG : src/item.cpp:605 [item& item::ammo_set(const itype_id&, int)] Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag
22:16:04.622 ERROR DEBUGMSG : src/item.cpp:605 [item& item::ammo_set(const itype_id&, int)] Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag
22:16:06.408 ERROR DEBUGMSG : src/item.cpp:605 [item& item::ammo_set(const itype_id&, int)] Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag
22:16:06.954 ERROR DEBUGMSG : src/item.cpp:605 [item& item::ammo_set(const itype_id&, int)] Tried to set invalid ammo sgs5_b[40] for metro_lolifebigmag

**Comment by Kenan2000** [comment]
@Spodershibe Hopefully fixed in this update as well
