### ISSUE TITLE
Invalid effect type id controlled

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#85]
invalid effect type id controlled
08:24:46.727 ERROR DEBUGMSG : src/effect.cpp:53 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id controlled
08:24:47.351 ERROR DEBUGMSG : src/effect.cpp:53 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id controlled
08:24:49.829 ERROR DEBUGMSG : src/effect.cpp:53 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id controlled
08:24:50.726 ERROR DEBUGMSG : src/creature.cpp:982 [virtual void Creature::add_effect(const efftype_id&, const time_duration&, const bodypart_str_id&, int, bool, bool)] Invalid effect, ID: 
08:24:50.893 ERROR DEBUGMSG : src/effect.cpp:53 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id controlled
08:24:51.029 ERROR DEBUGMSG : src/creature.cpp:982 [virtual void Creature::add_effect(const efftype_id&, const time_duration&, const bodypart_str_id&, int, bool, bool)] Invalid effect, ID: 
08:24:51.470 ERROR DEBUGMSG : src/effect.cpp:53 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id controlled

This appears to happen rarely during mapgen, no idea how to tell which mod is causing this

**Comment by Kenan2000** [comment]
@Spodershibe Hopefully fixed in this update as well
