### ISSUE TITLE
Game breaking error "item_location lost its target item during a save/load cycle"

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#87]
I don't know what is causing this, other than the fact that it has occurred for me when I try to place items anywhere, sometimes, seems to happen more frequently with more items in the space

item_location lost its target item during a save/load cycle
09:58:59.887 ERROR DEBUGMSG : src/activity_item_handling.cpp:578 [bool pickup::try_rebuild_if_needed(item_location&)] Lost target item of ACT_DROP and couldn't rebuild item_location!
09:59:00.814 ERROR DEBUGMSG : src/activity_item_handling.cpp:597 [std::__cxx11::list<item> pickup::obtain_and_tokenize_items(player&, std::__cxx11::list<pickup::act_item>&)] Lost target item of ACT_DROP
09:59:03.322 ERROR DEBUGMSG : src/item_location.cpp:106 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
09:59:04.689 ERROR DEBUGMSG : src/activity_item_handling.cpp:578 [bool pickup::try_rebuild_if_needed(item_location&)] Lost target item of ACT_DROP and couldn't rebuild item_location!
09:59:05.192 ERROR DEBUGMSG : src/item_location.cpp:106 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
09:59:05.224 ERROR DEBUGMSG : src/activity_item_handling.cpp:578 [bool pickup::try_rebuild_if_needed(item_location&)] Lost target item of ACT_DROP and couldn't rebuild item_location!
09:59:05.269 ERROR DEBUGMSG : src/item_location.cpp:106 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
09:59:05.301 ERROR DEBUGMSG : src/activity_item_handling.cpp:578 [bool pickup::try_rebuild_if_needed(item_location&)] Lost target item of ACT_DROP and couldn't rebuild item_location!
09:59:05.331 ERROR DEBUGMSG : src/item_location.cpp:106 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle

The two lines here then repeat on indefinitely until I close the game

**Comment by Kenan2000** [comment]
@Spodershibe This is from one of builds, a source code issue, not related to mods as well
