### ISSUE TITLE
 invalid item group 'guns_shotgun_ww2', om_terrain = 'museum_north' (museum)

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#89]
place_items: invalid item group 'guns_shotgun_ww2', om_terrain = 'museum_north' (museum)
03:10:14.188 ERROR DEBUGMSG : src/mapgen.cpp:5531 [std::vector<item*> map::place_items(const item_group_id&, int, const tripoint&, const tripoint&, bool, const time_point&, int, int)] place_items: invalid item group 'ammo_shotgun_ww2', om_terrain = 'museum_north' (museum)

This occurs only sometimes when generating a museum building in a city

**Comment by Kenan2000** [comment]
@Spodershibe Hopefully fixed in this update as well
