### ISSUE TITLE
Contacting mod authours

### ISSUE THREAD

**Issue by budgetcommander** [Kenan2000/BrightNights-Structured-Kenan-Modpack#99]
Is there any way for me to contact a mod authour? I'd like to make some description touchups for Advanced Technology, but I want them to approved by the mod authour themselves.

**Comment by Kenan2000** [comment]
@budgetcommander One of Advanced Technologies authors is MechMaster, you can contact him on our Bright Nights server https://discord.gg/anfcTzyA, here as well
